Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Huelton Santos
// Autor(a)    : Jéssica Andrade
// Data atual  : 14/01/2021
Var
// Seção de Declarações das variáveis
   nome,sobreNome: caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("Digite o seu nome: ")
   leia(nome)
   
   escreva("Digite o seu sobrenome: ")
   leia(sobreNome)

   escreva("Bem vindo ",nome," ",sobreNome)


Fimalgoritmo